export {
  loginSchema,
  magicLinkRequestSchema,
  magicLinkVerifySchema,
  completeSignupSchema,
  forgotPasswordSchema,
  resetPasswordSchema,
  type LoginInput,
  type MagicLinkRequestInput,
  type MagicLinkVerifyInput,
  type CompleteSignupInput,
  type ForgotPasswordInput,
  type ResetPasswordInput,
} from "./auth";

export {
  createTenantSchema,
  updateTenantSchema,
  createLocationSchema,
  updateLocationSchema,
  createTenantWizardSchema,
  resolveDomainSchema,
  listTenantsQuerySchema,
  updateTenantSettingsSchema,
  type CreateTenantInput,
  type UpdateTenantInput,
  type CreateLocationInput,
  type UpdateLocationInput,
  type CreateTenantWizardInput,
  type ResolveDomainInput,
  type ListTenantsQuery,
  type UpdateTenantSettingsInput,
} from "./tenant";

export {
  createTherapistSchema,
  updateTherapistSchema,
  updateTherapistProfileSchema,
  listTherapistsQuerySchema,
  createAssignmentSchema,
  type CreateTherapistInput,
  type UpdateTherapistInput,
  type UpdateTherapistProfileInput,
  type ListTherapistsQuery,
  type CreateAssignmentInput,
} from "./therapist";

export {
  createProgramSchema,
  updateProgramSchema,
  listProgramsQuerySchema,
  generateSlotsSchema,
  listAvailabilitySlotsSchema,
  availabilityOverviewSchema,
  type CreateProgramInput,
  type UpdateProgramInput,
  type ListProgramsQuery,
  type GenerateSlotsInput,
  type ListAvailabilitySlotsQuery,
  type AvailabilityOverviewQuery,
} from "./program";

export {
  createAppointmentSchema,
  listEmployeeAppointmentsSchema,
  cancelAppointmentSchema,
  updateEmployeeProfileSchema,
  changePasswordSchema,
  availableDatesQuerySchema,
  availableSlotsQuerySchema,
  type CreateAppointmentInput,
  type ListEmployeeAppointmentsQuery,
  type CancelAppointmentInput,
  type UpdateEmployeeProfileInput,
  type ChangePasswordInput,
  type AvailableDatesQuery,
  type AvailableSlotsQuery,
} from "./appointment";
